# Generated by Django 4.2.3 on 2024-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_initiatedpayments_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatedpayments',
            name='object_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='initiatedpayments',
            name='purpose',
            field=models.CharField(max_length=30),
        ),
    ]
