# Generated by Django 4.2.3 on 2024-02-14 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Pastor', 'Pastor'), ('ADMINISTRATOR', 'Admin'), ('Supervisor', 'Supervisor')], default='Member', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.PositiveIntegerField()),
                ('verse', models.PositiveIntegerField()),
                ('word', models.TextField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(null=True)),
                ('l_name', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('profile_pic', models.FileField(upload_to='ProfilePics/')),
                ('google_pic', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('points', models.PositiveIntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.myuser',),
            managers=[
                ('member', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.myuser',),
            managers=[
                ('pastor', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.myuser',),
            managers=[
                ('partner', django.db.models.manager.Manager()),
            ],
        ),
    ]
