# Generated by Django 4.2.3 on 2024-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usertheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='google_pic',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
