# Generated by Django 4.2.3 on 2024-01-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_personalprofile_google_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='ProfilePics/'),
        ),
    ]
