# Generated by Django 4.2.3 on 2024-01-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
