# Generated by Django 4.2.3 on 2024-01-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleStudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('bible_id', models.CharField(max_length=100)),
            ],
        ),
    ]
