# Generated by Django 4.2.3 on 2024-01-18 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BibleStudy', '0004_books_chapters_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='book',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='BibleStudy.books'),
        ),
    ]
