# Generated by Django 4.2.3 on 2024-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleStudy', '0006_achievements_alter_progress_book_myachievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_id',
            field=models.CharField(default='MAT', max_length=30),
        ),
    ]
