# Generated by Django 4.2.3 on 2024-01-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleStudy', '0007_books_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='location',
            field=models.CharField(choices=[('NT', 'NT'), ('OT', 'OT')], default='NT', max_length=15),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.CharField(max_length=30),
        ),
    ]
