# Generated by Django 4.2.3 on 2024-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleStudy', '0009_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='word',
            field=models.TextField(default='None', max_length=1000),
        ),
    ]
