# Generated by Django 4.2.3 on 2024-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibleStudy', '0010_bookmarks_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicalBookMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Faith', 'Faith'), ('Sin', 'Sin'), ('Sorrow', 'Sorrow'), ('Thanks Giving', 'Thanks Giving'), ('Giving', 'Giving'), ('Living', 'Living'), ('Forgiving', 'Forgiving'), ('Encouragement', 'Encouragement')], max_length=100)),
                ('verse', models.CharField(max_length=30)),
                ('word', models.TextField(default='None', max_length=1000)),
            ],
        ),
    ]
