# Generated by Django 4.2.3 on 2024-02-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('verse', models.CharField(max_length=100)),
                ('word', models.TextField(max_length=1000)),
            ],
        ),
    ]
