# Generated by Django 4.2.3 on 2024-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyWord', '0002_alter_dailymessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymessage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
